### ISSUE TITLE
多线程问题

### ISSUE THREAD

**Issue by stard** [codercheng/sparrow#1]
我看了一下你的代码，不是很理解你在创建线程时，为什么每次新创建一个epfd，因为每个线程的epfd是相互独立的，怎么能从主线程的epfd中获取套接字的可读可写信息？

**Comment by codercheng** [comment]
@stard 这就是一个trick，这样做避免了主线程向工作线程传输数据。比如我在主线程中创建了3个epoll，然后他们需要分别跑在3个工作线程中，我想你的疑惑是，为什么我在主线程中注册了可读事件，在工作线程中还能触发？这些线程说白了属于一个进程，而创建一个epoll fd，他在整个进程中是共享的，如果我的监听逻辑写在工作线程中，那么就会从工作线程中触发，不管你是在哪个线程中注册的，因为epfd在进程中是唯一的，线程中是共享的。

**Comment by stard** [comment]
我之前看的epoll_wait里面的一个参数我理解错啦，一直以为参数events是从所对应的epfd得到，但看你解释之后有重新看了下，参数events用来从内核得到事件的集合，这样就相同啦，就像你说的那些工作线程共享所有的内核事件。  真是非常感谢。
